### ISSUE TITLE
clean notifications button was very close to the margin

### ISSUE THREAD

**Issue by caseca** [kylecorry31/gnome-shell-extension-do-not-disturb#10]
after activating the extension the clean notifications button was next to the separator line

**Comment by kylecorry31** [comment]
Can you post a screenshot?

**Comment by caseca** [comment]
![erro_dot_not_disturb](https://user-images.githubusercontent.com/4641681/46693515-5db42500-cbe0-11e8-8390-d19f3aa8d062.png)
