### ISSUE TITLE
Support gsettings API

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/gnome-shell-extension-do-not-disturb#19]
* A gsettings API to enable or disable DND would be useful as other apps could tap into this extension to provide their users a distraction free (well, reduced) work environment.

**Comment by jackpot51** [comment]
Could this already be done with dconf and/or gsettings?

**Comment by kylecorry31** [comment]
Technically if you change the show-banners boolean in org.gnome.desktop.notifications, this extension will listen to that change and turn on/off, but I don't know if that is intuitive (plus you set show-banners to false to enable DND and true to disable, which is backwards).

I think gsettings would be easier though, so I am going to change this issue to that.
