### ISSUE TITLE
Broken in Shell 3.30.1

### ISSUE THREAD

**Issue by catb0t** [kylecorry31/gnome-shell-extension-do-not-disturb#20]
Updated to Ubuntu 18.10 with GNOME 3.30.1 and this appears to no longer work, I can try to find a log soon

**Comment by catb0t** [comment]
https://github.com/franglais125/no-title-bar/issues/93

**Comment by kylecorry31** [comment]
Hello,

I was unable to replicate this issue, can you provide a detailed log (use `journalctl -f | grep kylecorry31`)? Also, do you know which part does not work - what is the exact issue?

**Comment by catb0t** [comment]
After an update to this extension or GNOME Shell or something else, I don't think this extension errors anymore, but I will check again later and give more info that I can find. Thanks for reminding me to revisit this!
