### ISSUE TITLE
extension is not blocking notifications on gnome shell 3.30

### ISSUE THREAD

**Issue by hferreiro** [kylecorry31/gnome-shell-extension-do-not-disturb#22]

**Comment by kylecorry31** [comment]
I am unable to replicate this issue, can you provide more details (OS, GNOME shell version, log)?

**Comment by kylecorry31** [comment]
Can you also verify if toggling the extension on disables the 'show notification banner' setting within GNOME settings?

**Comment by hferreiro** [comment]
After a few days with the extension, it seems to only happen with some notifications coming from the browser. In particular, notifications from Hangouts chats and Google Calendar.

**Comment by kylecorry31** [comment]
Hello, which browser are you using? Also, is the notification a pop-up notification or just sound?

**Comment by hferreiro** [comment]
Google Chrome. It's the pop-up, not sure about sound.

**Comment by kylecorry31** [comment]
I am unable to replicate this issue on Pop!_OS 18.10.

Which operating system are you using?

**Comment by alosarjos** [comment]
I just tested it with Spotify notifications when changing song and it's working nicely on my Pop!_OS 18.10

Also tested this page: http://www.bennish.net/web-notifications.html with Firefox and still working.

**Comment by hferreiro** [comment]
I'm using Fedora 29

**Comment by alosarjos** [comment]
Maybe it's something related to Wayland then? Fedora uses Wayland session by default while Pop!_OS Xorg. I have found in the past some incompatibilities with other extensions on Wayland.

**Comment by kylecorry31** [comment]
That is possible, I will have some time to test on Fedora 29 later this week.

**Comment by kylecorry31** [comment]
I just tried to replicate this issue on Fedora 29 and was unable to replicate. Please ensure that you are running the latest version of the extension and if the problem persists, reopen this issue and provide a log (`journalctl -f | grep kylecorry`).

**Comment by hferreiro** [comment]
There are no messages from the extension besides the extension update in the journal. I noticed the problem is with the hangouts extension, not with browser notifications.

**Comment by kylecorry31** [comment]
I was able to confirm this with the hangouts extension - I can't replicate with any other Google Chrome notifications - so it must be the way Hangouts is delivering notifications...

**Comment by kylecorry31** [comment]
So upon further testing, I found that this is a problem with Chrome not using standard Gnome APIs - none of the system settings are able to block notifications (and using the same sources in firefox produce the expected results).

I will see what I can do to create an upstream issue in chromium to get them to use the default Gnome notification APIs.

**Comment by alosarjos** [comment]
https://www.omgubuntu.co.uk/2017/04/google-chrome-dev-lets-enable-native-desktop-notifications

Is this flag working? Can't test now.

**Comment by kylecorry31** [comment]
That fixes this issue, thanks!
