### ISSUE TITLE
Error window instead of settings window in GNOME Tweaks

### ISSUE THREAD

**Issue by junksignup** [kylecorry31/gnome-shell-extension-do-not-disturb#23]
>Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found
>
>Stack trace:
>  @/home/ramuyko/.local/share/gnome-shell/extensions/web_search_dialog@awamper.gmail.com/utils.js:17:7
>  @/home/ramuyko/.local/share/gnome-shell/extensions/web_search_dialog@awamper.gmail.com/prefs.js:26:7
>  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
>  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
>  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
>  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
>  @<main>:1:43

Updated the extension (autoupdate was turned off), but the problem remained.

Found an advice to do `sudo apt-get install gir1.2-clutter-1.0 gir1.2-clutter-gst-3.0 gir1.2-gtkclutter-1.0`. Result:

>Error: Requiring Shell, version none: Requiring namespace 'Clutter' version '2', but '1.0' is already loaded
>
>Stack trace:
>  @resource:///org/gnome/shell/misc/util.js:10:7
>  @/home/biasedagent/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/settings.js:5:7
>  @/home/biasedagent/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/prefs.js:8:7
>  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
>  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
>  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
>  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
>  @<main>:1:43

**Comment by junksignup** [comment]
P.S.: I'm on Ubuntu 18.04, GNOME Shell version — 3.28.3.

**Comment by cgiannakidis70** [comment]
Same here in Ubuntu 18.04.1 Gnome Shell  version - 3.28.2

**Comment by v-marinkov** [comment]
This is the one I get on PopOS 18.10 
```
ImportError: No JS module 'util' found in search path

Stack trace:
  @/home/viktor/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/settings.js:5:7
  @/home/viktor/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/prefs.js:8:7
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:67:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:82:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43
  ```
