### ISSUE TITLE
Gnome 3.32 bell not showing

### ISSUE THREAD

**Issue by tiotrom** [kylecorry31/gnome-shell-extension-do-not-disturb#40]
Manjaro Gnome Stable.
![2019-03-30_01-04](https://user-images.githubusercontent.com/34804533/55268192-cd4dc780-5287-11e9-91d5-f04d1fad1080.png)

**Comment by kylecorry31** [comment]
Can you provide the following information:
 
 
**Do not disturb settings (run `gsettings --schemadir ~/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/schemas list-recursively org.gnome.shell.extensions.kylecorry31-do-not-disturb`):**



**Log output (`journalctl -b | grep donotdisturb@kylecorry31`)**

**Comment by tiotrom** [comment]
Do not disturb settings

```
[tio@tio-pc ~]$ gsettings --schemadir ~/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/schemas list-recursively org.gnome.shell.extensions.kylecorry31-do-not-disturb
org.gnome.shell.extensions.kylecorry31-do-not-disturb do-not-disturb true
org.gnome.shell.extensions.kylecorry31-do-not-disturb show-count true
org.gnome.shell.extensions.kylecorry31-do-not-disturb mute-sounds false
org.gnome.shell.extensions.kylecorry31-do-not-disturb show-dot false
org.gnome.shell.extensions.kylecorry31-do-not-disturb show-icon true
```
Log output
```
[tio@tio-pc ~]$ journalctl -b | grep donotdisturb@kylecorry31
mar 30 05:40:16 tio-pc org.gnome.Shell.desktop[1677]: #0   55788b043f18 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/widgets.js:204 (7f66d6b6c0d0 @ 97)
mar 30 05:40:16 tio-pc org.gnome.Shell.desktop[1677]: #1   55788b043e88 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/extension.js:49 (7f66d6b3dca0 @ 77)
mar 30 05:40:16 tio-pc org.gnome.Shell.desktop[1677]: #0   55788b043f18 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/widgets.js:206 (7f66d6b6c0d0 @ 128)
mar 30 05:40:16 tio-pc org.gnome.Shell.desktop[1677]: #1   55788b043e88 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/extension.js:49 (7f66d6b3dca0 @ 77)
mar 30 12:02:09 tio-pc org.gnome.Shell.desktop[1677]: #0   5578985c2a80 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/widgets.js:204 (7f66d6b6c0d0 @ 97)
mar 30 12:02:09 tio-pc org.gnome.Shell.desktop[1677]: #1   5578985c29f0 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/extension.js:49 (7f66d6b3dca0 @ 77)
mar 30 12:02:09 tio-pc org.gnome.Shell.desktop[1677]: #0   5578985c2a80 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/widgets.js:206 (7f66d6b6c0d0 @ 128)
mar 30 12:02:09 tio-pc org.gnome.Shell.desktop[1677]: #1   5578985c29f0 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/extension.js:49 (7f66d6b3dca0 @ 77)
mar 30 12:16:59 tio-pc org.gnome.Shell.desktop[1677]: #0   5558ae7d3070 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/widgets.js:204 (7f3699f6a0d0 @ 97)
mar 30 12:16:59 tio-pc org.gnome.Shell.desktop[1677]: #1   5558ae7d2fe0 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/extension.js:49 (7f3699f3cca0 @ 77)
mar 30 12:16:59 tio-pc org.gnome.Shell.desktop[1677]: #0   5558ae7d3070 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/widgets.js:206 (7f3699f6a0d0 @ 128)
mar 30 12:16:59 tio-pc org.gnome.Shell.desktop[1677]: #1   5558ae7d2fe0 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/extension.js:49 (7f3699f3cca0 @ 77)
mar 30 12:25:26 tio-pc org.gnome.Shell.desktop[1677]: #0   55ad54a8fee0 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/widgets.js:204 (7fae6f8b0d30 @ 97)
mar 30 12:25:26 tio-pc org.gnome.Shell.desktop[1677]: #1   55ad54a8fe50 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/extension.js:49 (7fae6f718160 @ 77)
mar 30 12:25:26 tio-pc org.gnome.Shell.desktop[1677]: #0   55ad54a8fee0 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/widgets.js:206 (7fae6f8b0d30 @ 128)
mar 30 12:25:26 tio-pc org.gnome.Shell.desktop[1677]: #1   55ad54a8fe50 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/extension.js:49 (7fae6f718160 @ 77)
mar 30 13:44:57 tio-pc gnome-shell[1677]: Extension donotdisturb@kylecorry31.github.io already installed in /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io. /usr/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io will not be loaded
mar 30 13:45:27 tio-pc org.gnome.Shell.desktop[1677]: #0   55ab0a420c18 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/widgets.js:204 (7f01f1b6a0d0 @ 97)
mar 30 13:45:27 tio-pc org.gnome.Shell.desktop[1677]: #1   55ab0a420b88 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/extension.js:49 (7f01f1b3cca0 @ 77)
mar 30 13:45:27 tio-pc org.gnome.Shell.desktop[1677]: #0   55ab0a420c18 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/widgets.js:206 (7f01f1b6a0d0 @ 128)
mar 30 13:45:27 tio-pc org.gnome.Shell.desktop[1677]: #1   55ab0a420b88 i   /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/extension.js:49 (7f01f1b3cca0 @ 77)
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/settings.js
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/locale/es/LC_MESSAGES/gnome-shell-extension-do-not-disturb.mo
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/extension.js
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/schemas/org.gnome.shell.extensions.kylecorry31-do-not-disturb.gschema.xml
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/locale/pt/LC_MESSAGES/gnome-shell-extension-do-not-disturb.po
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/lib.js
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/widgets.js
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/schemas/gschemas.compiled
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/stylesheet.css
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/dnd-symbolic.svg
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/prefs.js
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/locale/es/LC_MESSAGES/gnome-shell-extension-do-not-disturb.po
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/locale/fr/LC_MESSAGES/gnome-shell-extension-do-not-disturb.po
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/locale/fr/LC_MESSAGES/gnome-shell-extension-do-not-disturb.mo
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/system.js
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:   inflating: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/locale/pt/LC_MESSAGES/gnome-shell-extension-do-not-disturb.mo
mar 30 14:31:00 tio-pc org.gnome.Shell.desktop[1677]:  extracting: /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/metadata.json
[tio@tio-pc ~]$ 

```

**Comment by kylecorry31** [comment]
Hello, please try installing from source to see if the latest commits fix this problem: https://github.com/kylecorry31/gnome-shell-extension-do-not-disturb#build-from-sources-optional

The log file you sent seems to be consistent with the issues that were just fixed today, and I am unable to replicate this problem on the latest sources.

**Comment by tiotrom** [comment]
@kylecorry31  it does not unfortunately...tomorrow I will try on a few other machines with manjaro to see if the issue is only on my computer. Will update you tomorrow. Cheers!

**Comment by kylecorry31** [comment]
I also forgot to mention that after you install from sources, you need to restart the GNOME shell (Alt+F2 -> R -> Enter). If you have already done that and are still experiencing this issue, could you provide me with another log output: `journalctl -b | grep donotdisturb@kylecorry31`

Also, do you have any icon packs installed?

**Comment by tiotrom** [comment]
Yes I restarted.

```
[tio@tio-pc ~]$ journalctl -b | grep donotdisturb@kylecorry31
[tio@tio-pc ~]$ 
```
I am using Zafiro icons. But tried with Papirus too.

**Comment by tiotrom** [comment]
Ok so it is a bit weird. Let me test more. I then switched to papirus icons and restarted the shell and it works. Switching back to Zafiro works too. Now, if I restart the shell it still works in paiprus but doesn't with Zafiro icons. So, maybe this is related to Zafiro icons?

**Comment by kylecorry31** [comment]
So what the extension tries to do is use the default "notification-disabled-symbolic" icon, and it that does not exist, it will fall back to the one that comes with it (Papirus themed). If the Zafiro icons have that notification-disabled-symbolic icon, but it is invisible or blank, that could explain what is happening. 

In theory, I could just make it load its own icon instead of using the theme's icon, though I'm not completely sure if I should - let me think on this a bit.

**Comment by tiotrom** [comment]
So you know I tested on other Manjaro installations and it is the same. Probably it works with Papirus but doesn't work with Zafori. Didn't test other icon packages. Also, this happened after the latest Gnome 3.32 update. As I remember it worked before that. I think you could also use a default icon instead of relying on an icon theme, could be more reliable. Cheers!

**Comment by kylecorry31** [comment]
Hello, can you install the extension from the latest sources and then restart the GNOME shell and see if this issue is resolved? I made the provided icon the default, so I believe this should fix this issue (I tried it with Zafori icons and it worked)

**Comment by tiotrom** [comment]
Still doesn0t work here. Maybe I need to completely wipe it out first? How do I properly do that?

**Comment by kylecorry31** [comment]
That's odd, let's try that. 

You can uninstall using the Gnome Tweak Tool. Just in case you can also run:
```
rm -rf ~/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/
```

And then install and restart the Gnome shell. Also, just in case, when installing from sources, make sure you clone the repository rather than downloading from the releases.

**Comment by tiotrom** [comment]
Ok I did all that and still doesn't work:
```

[tio@tio-pc ~]$ rm -rf ~/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/
[tio@tio-pc ~]$ git clone https://github.com/kylecorry31/gnome-shell-extension-do-not-disturb
fatal: destination path 'gnome-shell-extension-do-not-disturb' already exists and is not an empty directory.
[tio@tio-pc ~]$ git clone https://github.com/kylecorry31/gnome-shell-extension-do-not-disturb
Cloning into 'gnome-shell-extension-do-not-disturb'...
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 630 (delta 61), reused 60 (delta 31), pack-reused 537
Receiving objects: 100% (630/630), 1.44 MiB | 2.92 MiB/s, done.
Resolving deltas: 100% (400/400), done.
[tio@tio-pc ~]$ cd gnome-shell-extension-do-not-disturb
[tio@tio-pc gnome-shell-extension-do-not-disturb]$ make install
UUID is "donotdisturb@kylecorry31.github.io"
glib-compile-schemas ./src/schemas/
msgfmt -c src/locale/pt/LC_MESSAGES/gnome-shell-extension-do-not-disturb.po -o src/locale/pt/LC_MESSAGES/gnome-shell-extension-do-not-disturb.mo
msgfmt -c src/locale/es/LC_MESSAGES/gnome-shell-extension-do-not-disturb.po -o src/locale/es/LC_MESSAGES/gnome-shell-extension-do-not-disturb.mo
msgfmt -c src/locale/fr/LC_MESSAGES/gnome-shell-extension-do-not-disturb.po -o src/locale/fr/LC_MESSAGES/gnome-shell-extension-do-not-disturb.mo
rm -rf _build
mkdir -p _build
cp -r src/* _build
rm -rf /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io
mkdir -p /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io
cp -r _build/* /home/tio/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/
[tio@tio-pc gnome-shell-extension-do-not-disturb]$ 

```
But here's something: where is the extension cache stored? Because say I install it and I tweak its settings to show a dot instead of the number of notifications. Now I remove it completely like you suggested, and reinstall as you suggested, and I see the same setting with the dot instead of number is kept. I am thinking that it stores some settings somewhere and maybe that's why it doesn't work here. I need to somehow remove any trace of this extension and add it again brand new. Thoughts?

**Comment by kylecorry31** [comment]
This is really weird. Maybe try this:

```
rm -rf ~/.local/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/
rm -rf /usr/share/gnome-shell/extensions/donotdisturb@kylecorry31.github.io/
```

The second one may require sudo. Then restart the GNOME shell and open up the gnome tweak tool and verify that the extension no longer shows up. Then reinstall as you did above and see if that helps. Also, try toggling the 'show icon' setting on and off.  

The cache is stored within that folder you are deleting, so that makes me think that it is somehow falling back to the globally installed extension (from the GNOME store)

**Comment by tiotrom** [comment]
Not working and the settings are cached somewhere...here's a video I did to show you https://vimeo.com/328975639/35bcb17d45

**Comment by kylecorry31** [comment]
Ok, I am going to forward this to the people at System76 and see if they can provide any insight into this. I'm not sure where the settings are being cached either.

**Comment by tiotrom** [comment]
Ok thank you I am very curious too. Please update here when you get an answer.

**Comment by kylecorry31** [comment]
Will do, it must be due to something like that (or something else in your configuration). This was what I got when testing on the latest Manjaro GNOME with the latest Zafiro icons (fresh install).

![Screenshot from 2019-04-07 15-56-59](https://user-images.githubusercontent.com/5938560/55689055-37ccca80-594e-11e9-93fa-70b3f54c548d.png)

**Comment by tiotrom** [comment]
Yea I wonder why is not working for me....or other laptops I tried with Manjaro that had this extension previously installed from gnome extensions website...

**Comment by kylecorry31** [comment]
Yeah, this is weird. I just tried it using the extension store and it worked on my fresh install. One more thing to try -> try uninstalling it through the extension store (install it and remove it if it doesn't appear): https://extensions.gnome.org/local/

Then install from sources again, and if it still does it, can you send me a log output again (`journalctl -b | grep kylecorry`)

Thank you

**Comment by tiotrom** [comment]
Ok I did all that. You can see a video here https://vimeo.com/329359027/9dbddb4b6a

Not much luck. I am baffled as to where the settings are stored since it remembers these settings despite completely removing the extension in multiple ways.

**Comment by kylecorry31** [comment]
I was finally able to replicate this on Ubuntu 19.04 with the latest GNOME shell. I believe I have fixed this problem as it is now showing the icon for me again. 

Let me know if this helped you.

**Comment by tiotrom** [comment]
Ok please tell me which one to test. This one https://github.com/pop-os/gnome-shell-extension-do-not-disturb ?

**Comment by kylecorry31** [comment]
My bad, as of right now either one works, but preferably test the one on pop-os. You can leave a comment here though and if it is still an issue, I will migrate this thread to the pop-os repo.

**Comment by tiotrom** [comment]
It works! Is that one going to be posted on gnome extensions website too? So happy you fixed it! Thank you!

**Comment by kylecorry31** [comment]
Yes, it will, I'm not sure if it will be posted there going forward but you can always install from source on the pop-os repo (I no longer have the time/resources to fully maintain this extension and have handed it over to System76).

Glad it worked!
