### ISSUE TITLE
UX thoughts upon looking at the extension in Pop!_OS 18.04

### ISSUE THREAD

**Issue by brs17** [kylecorry31/gnome-shell-extension-do-not-disturb#5]
Noticed that I get that white circle notification next to the time whenever a notification is received that wasn't displayed as a popup notification (it shows up when DND is off and I get a handful of notifications all at once or immediately if DND is on). 

I was thinking if it's possible, we would probably like to hide that dot when DND is enabled(otherwise you're still getting a notification).

Also thinking that the DND icon (slashed-out bell), makes more sense, if possible, in place of that white dot notification next to the clock since it is directly associated with notifications. Also because all of the icons on the right side have associated actions that can be done in that corner (where as the DND switch is in the notification menu). If the above is possible, I think enabling the icon by default would be desired.

**Comment by kylecorry31** [comment]
Thanks for the feedback, I'll take a look this weekend and see what I can do.

**Comment by kylecorry31** [comment]
All requests were implemented in the last few commits. The white circle notification was added as an option in the settings and the bell was moved and enabled by default.
