### ISSUE TITLE
Publish to Gnome extensions website

### ISSUE THREAD

**Issue by lionirdeadman** [kylecorry31/gnome-shell-extension-do-not-disturb#8]
To make it easier for people to install this, it'd be great if it were on https://extensions.gnome.org/.

Thanks! :)

**Comment by kylecorry31** [comment]
Great idea!

I just uploaded it, so it may take a bit of time for it to get approved. I'll update this issue when it is ready to download.

**Comment by lionirdeadman** [comment]
Thank you very much, looking forward to your update! 😀

**Comment by lionirdeadman** [comment]
Just noticed it was published.

Here's the link for anyone subscribed to this issue : https://extensions.gnome.org/extension/1480/do-not-disturb/
