### ISSUE TITLE
option to change label

### ISSUE THREAD

**Issue by caseca** [kylecorry31/gnome-shell-extension-do-not-disturb#9]
Option to change the label "Do not disturb"

**Comment by kylecorry31** [comment]
What would the use case where this label needs to be changed be?

**Comment by caseca** [comment]
In my case I would like to place the label in portuguese of brazil

**Comment by kylecorry31** [comment]
Good point, so maybe the issue is localization rather than being able to change the text of the label?

**Comment by caseca** [comment]
Yes but I thought using the location would be more laborious than changing the label

**Comment by kylecorry31** [comment]
I added support for translations based on the system language. Let me know if you experience any issues. I will add more support for other languages in the future.
